### ISSUE TITLE
Dimensional input

### ISSUE THREAD

**Issue by SlowDavinci** [CommonWealthRobotics/CaDoodle-Application#26] opened 2024-11-22 03:15 UTC
When you type in your dimensions for an object, and you press enter, it only records changes in the most recently changed dimension.. if you type in y then x and then hit enter it will only change the dimension for x. Awesome program btw. Hi from John

**Comment by madhephaestus** [comment] 2024-11-23 16:57
duplicate of https://github.com/CommonWealthRobotics/CaDoodle-Application/issues/9

**Closed by madhephaestus** 2024-11-23 16:57 UTC
